#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jul 15 21:34:39 2022

@author: michaelreuscher
"""


import tkinter as tk

calculation = ""
mr = 0


def add_to_calculation(symbol):
    global calculation
    calculation += str(symbol)
    text_result.delete(1.0, "end")
    text_result.insert(1.0, calculation)

def add_to_mplus():
    global calculation
    global mr
    mr += int(eval(calculation))
    clear_field()

def add_to_mminus():
    global calculation
    global mr
    mr -= int(eval(calculation))
    clear_field()

    
def add_mr():
    global calculation
    global mr
    clear_field()
    add_to_calculation(mr)
    
def evaluate_Calculation():
    global calculation
    try: 
        calculation = str(eval(calculation))
        text_result.delete(1.0, "end")
        text_result.insert(1.0, calculation)
    except:
        clear_field()
        text_result.insert(1.0, "ERROR")

def clear_field():
    global calculation
    calculation = ""
    text_result.delete(1.0, "end")
    
def all_clear():
    global calculation
    global mr
    calculation = ""
    mr =""
    text_result.delete(1.0, "end")
    
def clear_mr():
    global mr
    mr = 0



root = tk.Tk()
root.title("Rechner")
root.geometry("380x333") #für MAC 300x230  für Win 380x333
root.resizable(False, False)
root.config(bg= "grey")

text_result = tk.Text(root, height=2, width=21, font=("Arial", 24))
text_result.grid(columnspan=5)

btn_1 = tk.Button(root, text= "1", command=lambda: add_to_calculation(1), width=5, font=("Arial", 14))
btn_1.grid(row=2, column=1)
btn_2 = tk.Button(root, text= "2", command=lambda: add_to_calculation(2), width=5, font=("Arial", 14))
btn_2.grid(row=2, column=2)
btn_3 = tk.Button(root, text= "3", command=lambda: add_to_calculation(3), width=5, font=("Arial", 14))
btn_3.grid(row=2, column=3)
btn_4 = tk.Button(root, text= "4", command=lambda: add_to_calculation(4), width=5, font=("Arial", 14))
btn_4.grid(row=3, column=1)
btn_5 = tk.Button(root, text= "5", command=lambda: add_to_calculation(5), width=5, font=("Arial", 14))
btn_5.grid(row=3, column=2)
btn_6 = tk.Button(root, text= "6", command=lambda: add_to_calculation(6), width=5, font=("Arial", 14))
btn_6.grid(row=3, column=3)
btn_7 = tk.Button(root, text= "7", command=lambda: add_to_calculation(7), width=5, font=("Arial", 14))
btn_7.grid(row=4, column=1)
btn_8 = tk.Button(root, text= "8", command=lambda: add_to_calculation(8), width=5, font=("Arial", 14))
btn_8.grid(row=4, column=2)
btn_9 = tk.Button(root, text= "9", command=lambda: add_to_calculation(9), width=5, font=("Arial", 14))
btn_9.grid(row=4, column=3)
btn_0 = tk.Button(root, text= "0", command=lambda: add_to_calculation(0), width=5, font=("Arial", 14))
btn_0.grid(row=5, column=2)

btn_plus = tk.Button(root, text= "+", command=lambda: add_to_calculation("+"), width=5, font=("Arial", 14))
btn_plus.grid(row=2, column=4)
btn_minus = tk.Button(root, text= "-", command=lambda: add_to_calculation("-"), width=5, font=("Arial", 14))
btn_minus.grid(row=3, column=4)
btn_multi = tk.Button(root, text= "*", command=lambda: add_to_calculation("*"), width=5, font=("Arial", 14))
btn_multi.grid(row=4, column=4)
btn_div = tk.Button(root, text= "/", command=lambda: add_to_calculation("/"), width=5, font=("Arial", 14))
btn_div.grid(row=5, column=4)
btn_open = tk.Button(root, text= "(", command=lambda: add_to_calculation("("), width=5, font=("Arial", 14))
btn_open.grid(row=5, column=1)
btn_close = tk.Button(root, text= ")", command=lambda: add_to_calculation(")"), width=5, font=("Arial", 14))
btn_close.grid(row=5, column=3)
btn_point = tk.Button(root, text= ".", command=lambda: add_to_calculation("."), width=5, font=("Arial", 14))
btn_point.grid(row=6, column=4)


btn_result = tk.Button(root, text= "=", command= evaluate_Calculation, width=5, font=("Arial", 14))
btn_result.grid(row=7, column=4,)

btn_clear = tk.Button(root, text= "C", command= clear_field, width=5, font=("Arial", 14))
btn_clear.grid(row=7, column=1)
btn_allclear = tk.Button(root, text= "AC", command= all_clear, width=5, font=("Arial", 14))
btn_allclear.grid(row=7, column=2)

btn_mplus = tk.Button(root, text= "M+", command= add_to_mplus, width=5, font=("Arial", 14))
btn_mplus.grid(row=6, column=1)
btn_mminus = tk.Button(root, text= "M-", command= add_to_mminus, width=5, font=("Arial", 14))
btn_mminus.grid(row=6, column=2)
btn_mr = tk.Button(root, text= "MR", command= add_mr, width=5, font=("Arial", 14))
btn_mr.grid(row=6, column=3)
btn_mc = tk.Button(root, text= "MC", command= clear_mr, width=5, font=("Arial", 14))
btn_mc.grid(row=7, column=3)

root.mainloop()